//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialReclamo
    {
        public int NroDeHistorial { get; set; }
        public int NroDeReclamo { get; set; }
        public string NombreDeUsuario { get; set; }
        public string Observacion { get; set; }
        public decimal Longitud { get; set; }
        public decimal Latitud { get; set; }
        public System.DateTime FechaDeIngreso { get; set; }
        public string EstadoDelReclamo { get; set; }
        public System.DateTime FechaDeCambioDeEstado { get; set; }
    }
}
